DROP TABLE Countries

CREATE TABLE Countries (
    Id int ,
    Name varchar(255),
    Alpha2 varchar(5),
    Alpha3 varchar(5),
    PhoneCode varchar(50),
    Currency varchar(255),
    CurrencyCode varchar(5)
);

INSERT INTO Countries ("Name","Alpha2","Alpha3","PhoneCode","Currency","CurrencyCode")
VALUES(1,"Afghanistan","AF","AFG","93","Afghani","AFN"),
(2,"Aland Islands","AX","ALA","358","EURO","EUR"),
(3,"Albania","AL","ALB","355","Lek","ALL"),
(4,"Algeria","DZ","DZA","213","Algerian Dinar","DZD"),
(5,"American Samoa","AS","ASM","1-684","US Dollar","USD"),
(6,"Andorra","AD","AND","376","Euro","EUR"),
(7,"Angola","AO","AGO","244","Kwanza","AOA"),
(8,"Anguilla","AI","AIA","1-264","East Caribbean Dollar","XCD"),
(9,"Antarctica ","AQ","ATA","672","",""),
(10,"Antigua and Barbuda","AG","ATG","1-268","East Caribbean Dollar","XCD"),
(11,"Argentina","AR","ARG","54","Argentine Peso","ARS"),
(12,"Armenia","AM","ARM","374","Armenian Dram","AMD"),
(13,"Aruba","AW","ABW","297","Aruban Florin","AWG"),
(14,"Australia","AU","AUS","61","Australian Dollar","AUD"),
(15,"Austria","AT","AUT","43","Euro","EUR"),
(16,"Azerbaijan","AZ","AZE","994","Azerbaijanian Manat","AZN"),
(17,"Bahamas","BS","BHS","1-242","Bahamian Dollar","BSD"),
(18,"Bahrain","BH","BHR","973","Bahraini Dinar","BHD"),
(19,"Bangladesh","BD","BGD","880","Taka","BDT"),
(20,"Barbados","BB","BRB","1-246","Barbados Dollar","BBD"),
(21,"Belarus","BY","BLR","375","Belarussian Ruble","BYN"),
(22,"Belgium","BE","BEL","32","Euro","EUR"),
(23,"Belize","BZ","BLZ","501","Belize Dollar","BZD"),
(24,"Benin","BJ","BEN","229","CFA Franc BCEAO","XOF"),
(25,"Bermuda","BM","BMU","1-441","Bermudian Dollar","BMD"),
(26,"Bhutan","BT","BTN","975","Ngultrum","BTN, INR"),
(27,"Bolivia","BO","BOL","591","Boliviano,Mvdol","BOB, BOV"),
(28,"Bosnia and Herzegovina","BA","BIH","387","US Dollar, Convertible Mark","USD, BAM"),
(29,"Botswana","BW","BWA","267","Pula","BWP"),
(30,"Bouvet Island","BV","BVT","","Norwegian Krone","NOK"),
(31,"Brazil","BR","BRA","55","Brazilian Real","BRL"),
(32,"British Virgin Islands","VG","VGB","246","US Dollar","USD"),
(33,"British Indian Ocean Territory","IO","IOT","1-284","US Dollar","USD"),
(34,"Brunei Darussalam","BN","BRN","673","Brunei Dollar","BND"),
(35,"Bulgaria","BG","BGR","359","Bulgarian Lev","BGN"),
(36,"Burkina Faso","BF","BFA","226","CFA Franc BCEAO","XOF"),
(37,"Burundi","BI","BDI","257","Burundi Franc","BIF"),
(38,"Cambodia","KH","KHM","855","Riel","KHR"),
(39,"Cameroon","CM","CMR","237","CFA Franc BEAC","XAF"),
(40,"Canada","CA","CAN","1","Canadian Dollar","CAD"),
(41,"Cape Verde","CV","CPV","238","Cabo Verde Escudo","CVE"),
(42,"Cayman Islands ","KY","CYM","1-345","Cayman Islands Dollar","KYD"),
(43,"Central African Republic","CF","CAF","236","CFA Franc BEAC","XAF"),
(44,"Chad","TD","TCD","235","CFA Franc BEAC","XAF"),
(45,"Chile","CL","CHL","56","Chilean Peso,  Unidad de Fomento","CLP, CLF"),
(46,"China","CN","CHN","86","Yuan Renminbi","CNY"),
(47,"Hong Kong, SAR China","HK","HKG","852","Hong Kong Dollar","HKD"),
(48,"Macao, SAR China","MO","MAC","853","Pataca","MOP"),
(49,"Christmas Island","CX","CXR","61","Australian Dollar","AUD"),
(50,"Cocos (Keeling) Islands","CC","CCK","61","Australian Dollar","AUD"),
(51,"Colombia","CO","COL","57","Colombian Peso,Unidad de Valor Real","COU,COP"),
(52,"Comoros","KM","COM","269","Comoro Franc","KMF"),
(53,"Congo (Brazzaville) ","CG","COG","242","Congolese Franc, CFA Franc BEAC","CDF, XAF"),
(54,"Congo, (Kinshasa)","CD","COD","243","Congolese Franc, CFA Franc BEAC","CDF, XAF"),
(55,"Cook Islands ","CK","COK","682","New Zealand Dollar","NZD"),
(56,"Costa Rica","CR","CRI","506","Costa Rican Colon","CRC"),
(57,"Côte d'Ivoire","CI","CIV","225","CFA Franc BCEAO","XOF"),
(58,"Croatia","HR","HRV","385","Kuna","HRK"),
(59,"Cuba","CU","CUB","53","Cuban Peso, Peso Convertible","CUP, CUC"),
(60,"Curacao","CW","CUW","599","Netherlands Antillean Guilder","ANG"),
(61,"Cyprus","CY","CYP","357","Euro","EUR"),
(62,"Czech Republic","CZ","CZE","420","Czech Koruna","CZK"),
(63,"Democratic Republic of the Congo","CD","COD","243","Congolese Franc, CFA Franc BEAC","CDF, XAF"),
(64,"Denmark","DK","DNK","45","Danish Krone","DKK"),
(65,"Djibouti","DJ","DJI","253","Djibouti Franc","DJF"),
(66,"Dominica","DM","DMA","1-767","East Caribbean Dollar","XCD"),
(67,"Dominican Republic","DO","DOM","1-809, 1-829, 1-849","Dominican Peso","DOP"),
(68,"Ecuador","EC","ECU","593","US Dollar","USD"),
(69,"Egypt","EG","EGY","20","Egyptian Pound","EGP"),
(70,"El Salvador","SV","SLV","503","El Salvador Colon, East Timor","SVC, USD"),
(71,"Equatorial Guinea","GQ","GNQ","240","CFA Franc BEAC","XAF"),
(72,"Eritrea","ER","ERI","291","Nakfa","ERN"),
(73,"Estonia","EE","EST","372","Euro","EUR"),
(74,"Ethiopia","ET","ETH","251","Ethiopian Birr","ETB"),
(75,"Falkland Islands (Malvinas) ","FK","FLK","500","Falkland Islands Pound","FKP"),
(76,"Faroe Islands","FO","FRO","298","Danish Krone","DKK"),
(77,"Fiji","FJ","FJI","679","Fiji Dollar","FJD"),
(78,"Finland","FI","FIN","358","Euro","EUR"),
(79,"France","FR","FRA","33","Euro","EUR"),
(80,"French Guiana","GF","GUF","594","Euro","EUR"),
(81,"French Polynesia","PF","PYF","689","CFP Franc","XPF"),
(82,"French Southern Territories","TF","ATF","","Euro","EUR"),
(83,"Gabon","GA","GAB","241","CFA Franc BEAC","XAF"),
(84,"Gambia","GM","GMB","220","Dalasi","GMD"),
(85,"Georgia","GE","GEO","995","Lari","GEL"),
(86,"Germany","DE","DEU","49","Euro","EUR"),
(87,"Ghana","GH","GHA","233","Ghana Cedi","GHS"),
(88,"Gibraltar ","GI","GIB","350","Gibraltar Pound","GIP"),
(89,"Greece","GR","GRC","30","Euro","EUR"),
(90,"Greenland","GL","GRL","299","Danish Krone","DKK"),
(91,"Grenada","GD","GRD","1-473","East Caribbean Dollar","XCD"),
(92,"Guadeloupe","GP","GLP","590","Euro","EUR"),
(93,"Guam","GU","GUM","1-671","US Dollar","USD"),
(94,"Guatemala","GT","GTM","502","Quetzal","GTQ"),
(95,"Guernsey","GG","GGY","44-1481","Pound Sterling","GBP"),
(96,"Guinea","GN","GIN","224","Guinea Franc","GNF"),
(97,"Guinea-Bissau","GW","GNB","245","CFA Franc BCEAO","XOF"),
(98,"Guyana","GY","GUY","592","Guyana Dollar","GYD"),
(99,"Haiti","HT","HTI","509","Gourde, US Dollar","HTG, USD"),
(100,"Heard and Mcdonald Islands","HM","HMD","","Australian Dollar","AUD"),
(101,"Holy See (Vatican City State)","VA","VAT","379","Euro","EUR"),
(102,"Honduras","HN","HND","504","Lempira","HNL"),
(103,"Hungary","HU","HUN","36","Forint","HUF"),
(104,"Iceland","IS","ISL","354","Iceland Krona","ISK"),
(105,"India","IN","IND","91","Indian Rupee","INR"),
(106,"Indonesia","ID","IDN","62","Rupiah","IDR"),
(107,"Iran, Islamic Republic of","IR","IRN","98","Iranian Rial","IRR"),
(108,"Iraq","IQ","IRQ","964","Iraqi Dinar","IQD"),
(109,"Ireland","IE","IRL","353","Euro","EUR"),
(110,"Isle of Man ","IM","IMN","44-1624","Pound Sterling","GBP"),
(111,"Israel","IL","ISR","972","New Israeli Sheqel","ILS"),
(112,"Italy","IT","ITA","39","Euro","EUR"),
(113,"Jamaica","JM","JAM","1-876","Jamaican Dollar","JMD"),
(114,"Japan","JP","JPN","81","Yen","JPY"),
(115,"Jersey","JE","JEY","44-1534","Pound Sterling","GBP"),
(116,"Jordan","JO","JOR","962","Jordanian Dinar","JOD"),
(117,"Kazakhstan","KZ","KAZ","7","Tenge","KZT"),
(118,"Kenya","KE","KEN","254","Kenyan Shilling","KES"),
(119,"Kiribati","KI","KIR","686","Australian Dollar","AUD"),
(120,"Korea (North)","KP","PRK","850","North Korean Won","KPW"),
(121,"Korea (South)","KR","KOR","82","Won","KRW"),
(122,"Kosovo","XK","XKX","383","EUro","EUR"),
(123,"Kuwait","KW","KWT","965","Kuwaiti Dinar","KWD"),
(124,"Kyrgyzstan","KG","KGZ","996","Som","KGS"),
(125,"Lao PDR","LA","LAO","856","Kip","LAK"),
(126,"Latvia","LV","LVA","371","Euro","EUR"),
(127,"Lebanon","LB","LBN","961","Lebanese Pound","LBP"),
(128,"Lesotho","LS","LSO","266","Loti, Rand","LSL, ZAR"),
(129,"Liberia","LR","LBR","231","Liberian Dollar","LRD"),
(130,"Libya","LY","LBY","218","Libyan Dinar","LYD"),
(131,"Liechtenstein","LI","LIE","423","Swiss Franc","CHF"),
(132,"Lithuania","LT","LTU","370","Euro","EUR"),
(133,"Luxembourg","LU","LUX","352","Euro","EUR"),
(134,"Macedonia, Republic of","MK","MKD","389","Denar","MKD"),
(135,"Madagascar","MG","MDG","261","Malagasy Ariary","MGA"),
(136,"Malawi","MW","MWI","265","Kwacha","MWK"),
(137,"Malaysia","MY","MYS","60","Malaysian Ringgit","MYR"),
(138,"Maldives","MV","MDV","960","Rufiyaa","MVR"),
(139,"Mali","ML","MLI","223","CFA Franc BCEAO","XOF"),
(140,"Malta","MT","MLT","356","Euro","EUR"),
(141,"Marshall Islands","MH","MHL","692","US Dollar","USD"),
(142,"Martinique","MQ","MTQ","596","Euro","EUR"),
(143,"Mauritania","MR","MRT","222","Ouguiya","MRU"),
(144,"Mauritius","MU","MUS","230","Mauritius Rupee","MUR"),
(145,"Mayotte","YT","MYT","262","Euro","EUR"),
(146,"Mexico","MX","MEX","52","Mexican Peso ,Mexican Unidad de Inversion (UDI)","MXN,MXV"),
(147,"Micronesia, Federated States of","FM","FSM","691","US Dollar","USD"),
(148,"Moldova","MD","MDA","373","Moldovan Leu","MDL"),
(149,"Monaco","MC","MCO","377","Euro","EUR"),
(150,"Mongolia","MN","MNG","976","Tugrik","MNT"),
(151,"Montenegro","ME","MNE","382","Euro","EUR"),
(152,"Montserrat","MS","MSR","1-664","East Caribbean Dollar","XCD"),
(153,"Morocco","MA","MAR","212","Moroccan Dirham","MAD"),
(154,"Mozambique","MZ","MOZ","258","Mozambique Metical","MZN"),
(155,"Myanmar","MM","MMR","95","Kyat","MMK"),
(156,"Namibia","NA","NAM","264","Namibia Dollar, Rand","NAD, ZAR"),
(157,"Nauru","NR","NRU","674","Australian Dollar","AUD"),
(158,"Nepal","NP","NPL","977","Nepalese Rupee","NPR"),
(159,"Netherlands","NL","NLD","31","Euro","EUR"),
(160,"Netherlands Antilles","AN","ANT","599","ANG","ANG"),
(161,"New Caledonia","NC","NCL","687","CFP Franc","XPF"),
(162,"New Zealand","NZ","NZL","64","New Zealand Dollar","NZD"),
(163,"Nicaragua","NI","NIC","505","Cordoba Oro","NIO"),
(164,"Niger","NE","NER","227","CFA Franc BCEAO","XOF"),
(165,"Nigeria","NG","NGA","234","Naira","NGN"),
(166,"Niue ","NU","NIU","683","New Zealand Dollar","NZD"),
(167,"Norfolk Island","NF","NFK","","Australian Dollar","AUD"),
(168,"Northern Mariana Islands","MP","MNP","1-670","US Dollar","USD"),
(169,"Norway","NO","NOR","47","Norwegian Krone","NOK"),
(170,"Oman","OM","OMN","968","Rial Omani","OMR"),
(171,"Pakistan","PK","PAK","92","Pakistan Rupee","PKR"),
(172,"Palau","PW","PLW","680","US Dollar","USD"),
(173,"Palestinian Territory","PS","PSE","970","SHEKEL","ILS"),
(174,"Panama","PA","PAN","507","Balboa, US Dollar","PAB, USD"),
(175,"Papua New Guinea","PG","PNG","675","Kina","PGK"),
(176,"Paraguay","PY","PRY","595","Guarani","PYG"),
(177,"Peru","PE","PER","51","Nuevo Sol","PEN"),
(178,"Philippines","PH","PHL","63","Philippine Peso","PHP"),
(179,"Pitcairn","PN","PCN","64","New Zealand Dollar","NZD"),
(180,"Poland","PL","POL","48","Zloty","PLN"),
(181,"Portugal","PT","PRT","351","Euro","EUR"),
(182,"Puerto Rico","PR","PRI","1-787, 1-939","US Dollar","USD"),
(183,"Qatar","QA","QAT","974","Qatari Rial","QAR"),
(184,"Réunion","RE","REU","262","EURO","EUR"),
(185,"Romania","RO","ROU","40","Romanian Leu","RON"),
(186,"Russian Federation","RU","RUS","7","Russian Ruble","RUB"),
(187,"Rwanda","RW","RWA","250","Rwanda Franc","RWF"),
(188,"Saint-Barthélemy","BL","BLM","590","Euro","EUR"),
(189,"Saint Helena","SH","SHN","290","Saint Helena Pound","SHP"),
(190,"Saint Kitts and Nevis","KN","KNA","1-869","East Caribbean Dollar","XCD"),
(191,"Saint Lucia","LC","LCA","1-758","East Caribbean Dollar","XCD"),
(192,"Saint-Martin (French part)","MF","MAF","590","Euro","EUR"),
(193,"Saint Pierre and Miquelon ","PM","SPM","508","Euro","EUR"),
(194,"Saint Vincent and Grenadines","VC","VCT","1-784","East Caribbean Dollar","XCD"),
(195,"Samoa","WS","WSM","685","Tala","WST"),
(196,"San Marino","SM","SMR","378","Euro","EUR"),
(197,"Sao Tome and Principe","ST","STP","239","Dobra","STN"),
(198,"Saudi Arabia","SA","SAU","966","Saudi Riyal","SAR"),
(199,"Senegal","SN","SEN","221","CFA Franc BCEAO","XOF"),
(200,"Serbia","RS","SRB","381","Serbian Dinar","RSD"),
(201,"Seychelles","SC","SYC","248","Seychelles Rupee","SCR"),
(202,"Sierra Leone","SL","SLE","232","Leone","SLL"),
(203,"Singapore","SG","SGP","65","Singapore Dollar","SGD"),
(204,"Sint Maarten","sx","sxm","1-721","Netherlands Antillean Guilder","ANG"),
(205,"Slovakia","SK","SVK","421","Euro","EUR"),
(206,"Slovenia","SI","SVN","386","Euro","EUR"),
(207,"Solomon Islands","SB","SLB","677","Solomon Islands Dollar","SBD"),
(208,"Somalia","SO","SOM","252","Somali Shilling","SOS"),
(209,"South Africa","ZA","ZAF","27","Rand","ZAR"),
(210,"South Georgia and the South Sandwich Islands","GS","SGS","82","No universal currency",""),
(211,"South Sudan","SS","SSD","211","South Sudanese Pound","SSP"),
(212,"Spain","ES","ESP","34","Euro","EUR"),
(213,"Sri Lanka","LK","LKA","94","Sri Lanka Rupee","LKR"),
(214,"Sudan","SD","SDN","249","Sudanese Pound","SDG"),
(215,"Suriname","SR","SUR","597","Surinam Dollar","SRD"),
(216,"Svalbard and Jan Mayen Islands ","SJ","SJM","47","Norwegian Krone","NOK"),
(217,"Swaziland","SZ","SWZ","268","Lilangeni","SZL"),
(218,"Sweden","SE","SWE","46","Swedish Krona","SEK"),
(219,"Switzerland","CH","CHE","41","WIR Euro,Swiss Franc,Swiss Franc","CHE,CHF,CHW"),
(220,"Syrian Arab Republic (Syria)","SY","SYR","963","Syrian Pound","SYP"),
(221,"Taiwan, Republic of China ","TW","TWN","886","New Taiwan Dollar","TWD"),
(222,"Tajikistan","TJ","TJK","992","Somoni","TJS"),
(223,"Tanzania, United Republic of ","TZ","TZA","255","Tanzanian Shilling","TZS"),
(224,"Thailand","TH","THA","66","Baht","THB"),
(225,"Timor-Leste","TL","TLS","670","US dollar ","USD"),
(226,"Togo","TG","TGO","228","CFA Franc BCEAO","XOF"),
(227,"Tokelau ","TK","TKL","690","New Zealand Dollar","NZD"),
(228,"Tonga","TO","TON","676","Pa’anga","TOP"),
(229,"Trinidad and Tobago","TT","TTO","1-868","Trinidad and Tobago Dollar","TTD"),
(230,"Tunisia","TN","TUN","216","Tunisian Dinar","TND"),
(231,"Turkey","TR","TUR","90","Turkish Lira","TRY"),
(232,"Turkmenistan","TM","TKM","993","Turkmenistan New Manat","TMT"),
(233,"Turks and Caicos Islands ","TC","TCA","1-649","US Dollar","USD"),
(234,"Tuvalu","TV","TUV","688","Australian Dollar","AUD"),
(235,"Virgin Islands, US","VI","VIR","1-340","DOLLAR (USD)","USD"),
(236,"Uganda","UG","UGA","256","Uganda Shilling","UGX"),
(237,"Ukraine","UA","UKR","380","Hryvnia","UAH"),
(238,"United Arab Emirates","AE","ARE","971","UAE Dirham","AED"),
(239,"United Kingdom","GB","GBR","44","Pound Sterling","GBP"),
(240,"United States of America","US","USA","1","US Dollar","USD"),
(241,"US Minor Outlying Islands","UM","UMI","1","US Dollar","USD"),
(242,"Uruguay","UY","URY","598","US Dollar (Next day), Uruguay Peso en Unidades Indexadas (URUIURUI)","USN, UYI"),
(243,"Uzbekistan","UZ","UZB","998","Peso Uruguayo","UYU"),
(244,"Vanuatu","VU","VUT","678","Uzbekistan Sum","UZS"),
(245,"Venezuela (Bolivarian Republic)","VE","VEN","58","Vatu, Bolivar","VUV, VEF"),
(246,"Viet Nam","VN","VNM","84","Dong","VND"),
(247,"Wallis and Futuna Islands ","WF","WLF","681","CFP Franc","XPF"),
(248,"Western Sahara ","EH","ESH","212","Moroccan Dirham","MAD"),
(249,"Yemen","YE","YEM","967","Yemeni Rial","YER"),
(250,"Zambia","ZM","ZMB","260","Zambian Kwacha","ZMW"),
(251,"Zimbabwe","ZW","ZWE","263","Zimbabwe Dollar","ZWL"),
